// Generated by CoffeeScript 1.4.0
(function() {

  window.nimi = [
    {
      nimi: "a",
      sitelen: ["interj: ah, ha, uh, oh, ooh, aw, well (emotion word)"]
    }, {
      nimi: "akesi",
      sitelen: ["n: non-cute animal, reptile, amphibian"]
    }, {
      nimi: "ala",
      sitelen: ["mod: no, not, none, un-", "n: nothing, negation, zero", "interj: no!"]
    }, {
      nimi: "ale, ali",
      sitelen: ["n: everything, anything, life, the universe", "mod: all, every, complete, whole"]
    }
  ];

  /*
  {
  	nimi: "",
  	sitelen: [
  		""
  	]
  }
  */


}).call(this);
